import type { MedicalEvent } from './types'

export const mockEvents: MedicalEvent[] = [
  {
    id: '1',
    title: '2026 대한내과학회 춘계학술대회',
    specialty: '내과',
    region: '서울',
    isOnline: false,
    startDate: '2026-02-15',
    endDate: '2026-02-17',
    generalCredits: 8,
    requiredCredits: 4,
    totalCredits: 12,
    organizer: '대한내과학회',
    location: '서울 코엑스 컨벤션센터',
    contact: '02-1234-5678',
    notes: '사전등록 시 할인 혜택이 있습니다.',
  },
  {
    id: '2',
    title: '정형외과 최신 수술기법 워크숍',
    specialty: '정형외과',
    region: '부산',
    isOnline: false,
    startDate: '2026-02-20',
    endDate: '2026-02-21',
    generalCredits: 6,
    requiredCredits: 3,
    totalCredits: 9,
    organizer: '대한정형외과학회',
    location: '부산 벡스코',
    contact: '051-2345-6789',
    notes: '실습 포함 프로그램입니다.',
  },
  {
    id: '3',
    title: '온라인 의료윤리 세미나',
    specialty: '가정의학과',
    region: '온라인',
    isOnline: true,
    startDate: '2026-02-10',
    endDate: '2026-02-10',
    generalCredits: 2,
    requiredCredits: 2,
    totalCredits: 4,
    organizer: '대한의사협회',
    location: 'Zoom 온라인',
    contact: '02-9876-5432',
    notes: '필수 평점 인정 과정입니다.',
  },
  {
    id: '4',
    title: '소아청소년과 감염질환 심포지엄',
    specialty: '소아청소년과',
    region: '대전',
    isOnline: false,
    startDate: '2026-02-25',
    endDate: '2026-02-25',
    generalCredits: 4,
    requiredCredits: 2,
    totalCredits: 6,
    organizer: '대한소아청소년과학회',
    location: '대전컨벤션센터',
    contact: '042-3456-7890',
    notes: '',
  },
  {
    id: '5',
    title: '피부과 레이저 치료 실습 과정',
    specialty: '피부과',
    region: '서울',
    isOnline: false,
    startDate: '2026-02-28',
    endDate: '2026-03-01',
    generalCredits: 5,
    requiredCredits: 3,
    totalCredits: 8,
    organizer: '대한피부과학회',
    location: '서울대학교병원',
    contact: '02-5678-1234',
    notes: '실습 장비 제공됩니다.',
  },
  {
    id: '6',
    title: '정신건강의학과 인지행동치료 워크숍',
    specialty: '정신건강의학과',
    region: '경기',
    isOnline: false,
    startDate: '2026-03-05',
    endDate: '2026-03-06',
    generalCredits: 6,
    requiredCredits: 4,
    totalCredits: 10,
    organizer: '대한신경정신의학회',
    location: '분당서울대병원',
    contact: '031-4567-8901',
    notes: '사례 중심 교육입니다.',
  },
  {
    id: '7',
    title: '온라인 의료법 특강',
    specialty: '예방의학과',
    region: '온라인',
    isOnline: true,
    startDate: '2026-03-08',
    endDate: '2026-03-08',
    generalCredits: 2,
    requiredCredits: 2,
    totalCredits: 4,
    organizer: '대한의사협회',
    location: 'Webex 온라인',
    contact: '02-1111-2222',
    notes: '의료분쟁 예방 관련 내용입니다.',
  },
  {
    id: '8',
    title: '응급의학과 외상처치 시뮬레이션',
    specialty: '응급의학과',
    region: '대구',
    isOnline: false,
    startDate: '2026-03-10',
    endDate: '2026-03-12',
    generalCredits: 8,
    requiredCredits: 6,
    totalCredits: 14,
    organizer: '대한응급의학회',
    location: '경북대학교병원',
    contact: '053-5678-9012',
    notes: '시뮬레이션 센터에서 진행됩니다.',
  },
  {
    id: '9',
    title: '안과 백내장수술 최신 동향',
    specialty: '안과',
    region: '인천',
    isOnline: false,
    startDate: '2026-03-15',
    endDate: '2026-03-15',
    generalCredits: 3,
    requiredCredits: 2,
    totalCredits: 5,
    organizer: '대한안과학회',
    location: '인천길병원',
    contact: '032-6789-0123',
    notes: '',
  },
  {
    id: '10',
    title: '재활의학과 운동재활 컨퍼런스',
    specialty: '재활의학과',
    region: '광주',
    isOnline: false,
    startDate: '2026-03-18',
    endDate: '2026-03-19',
    generalCredits: 5,
    requiredCredits: 3,
    totalCredits: 8,
    organizer: '대한재활의학회',
    location: '조선대학교병원',
    contact: '062-7890-1234',
    notes: '스포츠 재활 특별 세션 포함.',
  },
  {
    id: '11',
    title: '영상의학과 AI 진단 세미나',
    specialty: '영상의학과',
    region: '서울',
    isOnline: true,
    startDate: '2026-03-20',
    endDate: '2026-03-20',
    generalCredits: 3,
    requiredCredits: 1,
    totalCredits: 4,
    organizer: '대한영상의학회',
    location: 'Teams 온라인',
    contact: '02-8901-2345',
    notes: 'AI 기반 영상판독 소개.',
  },
  {
    id: '12',
    title: '마취통증의학과 통증관리 심포지엄',
    specialty: '마취통증의학과',
    region: '울산',
    isOnline: false,
    startDate: '2026-03-22',
    endDate: '2026-03-23',
    generalCredits: 6,
    requiredCredits: 4,
    totalCredits: 10,
    organizer: '대한마취통증의학회',
    location: '울산대학교병원',
    contact: '052-9012-3456',
    notes: '만성통증 관리 중심.',
  },
  {
    id: '13',
    title: '이비인후과 두경부 종양 학술대회',
    specialty: '이비인후과',
    region: '제주',
    isOnline: false,
    startDate: '2026-03-25',
    endDate: '2026-03-27',
    generalCredits: 9,
    requiredCredits: 5,
    totalCredits: 14,
    organizer: '대한이비인후과학회',
    location: '제주국제컨벤션센터',
    contact: '064-0123-4567',
    notes: '해외 연자 초청 강연 포함.',
  },
  {
    id: '14',
    title: '산부인과 주산기 의학 세미나',
    specialty: '산부인과',
    region: '경남',
    isOnline: false,
    startDate: '2026-02-12',
    endDate: '2026-02-13',
    generalCredits: 5,
    requiredCredits: 3,
    totalCredits: 8,
    organizer: '대한산부인과학회',
    location: '경상대학교병원',
    contact: '055-1234-5678',
    notes: '고위험 임신 관리 중심.',
  },
  {
    id: '15',
    title: '신경외과 척추수술 마스터클래스',
    specialty: '신경외과',
    region: '충남',
    isOnline: false,
    startDate: '2026-02-18',
    endDate: '2026-02-20',
    generalCredits: 10,
    requiredCredits: 6,
    totalCredits: 16,
    organizer: '대한신경외과학회',
    location: '단국대학교병원',
    contact: '041-2345-6789',
    notes: '카데바 실습 포함 과정.',
  },
]
